### ISSUE TITLE
Support 3d layers in DFM BMI interface

### ISSUE THREAD

**Issue by erwin-mulder** [Deltares/libzsf#27]
D-Flow FM supplies water volumes and quantities in array form to support 3d layers.
We need to use the previously implemented layers and profile conversion to support BMI communication with zsf, while zsf still operates on scalar values.

**Comment by vrielin** [comment]
I did not review the changes in detail (yet).. I tried to run these 2 examples
```
p:\dflowfm\maintenance\JIRA\07000-07999\07576\02_test_models\1_lock_cycle-average\
p:\dflowfm\maintenance\JIRA\07000-07999\07576\02_test_models\1_lock_cycle-average_3D\
```
with this branch (and the current head of D-FlowFM main) and both runs end on:
 `assert(layers->number_of_layers > 0); in distribute_discharge_over_layers
`
I think number_of_layers is initialized to 0 but never updated. I can''t find the location where sealock_get_active_layers
is called. 

In the 3D example there is water_volume specified as exchange item in the dimr_config.xml. 
For the 2D example I think a num_layers = 1 and volumes = 1.0 init is needed? Or prevent calling the distribute methods?
